# Generated by Django 5.1.1 on 2024-09-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0002_alter_cvtemplateclass_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvtemplateclass',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
